### ISSUE TITLE
Label distance on cover photo

### ISSUE THREAD

**Issue by extraymond** [labsin/places-scope#1]
Hi! I really enjoy using your app, and would like to give some feedback as feature request.

1.It would be nice to have distance labelled on the cover photo, so people can have a more intuitive way of knowing the distance between places and themselves.

2.It would also be nice to have an evergoing list of places ranging more than the setup distance in the settings. So people can explore to further places more easily rather than setting the distance back and forth.

3.Instead of just having google map, it would be nice to include here map or other map apps too, so people can use the app best fit their interest.

I'm not really a programmer so I don't know if that' workable.
I really enjoy your app everyday, this is awesome, and get me to places really quick!!
This really makes ubuntu touch really a reality.
Thx for the pioneer work!

**Comment by SeSamSeg** [comment]
Hi,
Thanks for the interest, sorry for the late responce (didn't get an e-mail)
I thought not a lot of people were using my scope. Because there are two other scopes that do the same thing and have integration with yelp. (the Nearby scope only on the BQ and the aroundU scope https://uappexplorer.com/app/eu.michael-weimann.unity-scope-nearby
Point 2 was not possible when I last checked but should be able to do now.
The problem is that I don't have a ubuntu phone and no longer have a PC that supports VT for virtualisation (to run the emulator)

**Comment by SeSamSeg** [comment]
I've added the distance label. It's now in the store.
