### ISSUE TITLE
Improvment

### ISSUE THREAD

**Issue by ktatar156** [labsin/places-scope#3]
Hello,

did You consider to make that scope showing closest places first? For now, it's seems that scope showing places randomly. I must point that for now in latest 0.1.9 still no results in NearBy scope.

**Comment by SeSamSeg** [comment]
There is a bug in NearBy https://bugs.launchpad.net/scope-aggregator/+bug/1490828 that causes only the first keyword of a scope to be considered.
Should be fixed in the next ota

**Comment by SeSamSeg** [comment]
About showing closest fist, now it's sorted by prominence (Google maps rating, distance,... )
I might add it as option in the settings (and maybe also add a "only open"), but that'll only work when you search on keyword or on type (food, drinks). In my option, closest isn't allows best, that's why there is a radius.
